with-expecter: true
dir: "{{ .InterfaceDir }}/{{ .PackageName }}mocks"
mockname: "{{ .InterfaceName }}"
outpkg: "{{ .PackageName }}mocks"
filename: "{{ .InterfaceName | snakecase | lower }}_mock.go"
disable-version-string: true
packages:
  github.com/viqueen/go-template/pkg/pet:
    interfaces:
      Project: